"""Tests for iteration-2 retention (DESIGN.md "Retention (iteration 2,
magnets + turn-buttons)", issue #20, REV.B after adversarial review): the
drawer magnet-pair holes (drawer Back wall <-> divider), the FRONT-WALL
turn-button pivot hole (REV.B; REV.A's side-wall pivot holes are now a
regression guard, not a feature under test), the turn-button hardware
piece, and the magnet press-fit coupon.

Style follows test_svg_geometry.py: parse the real SVGs with
tests/svg_utils.py, existence-first, literal bounds -- and, for the
positional checks, an independent-datum cross-check (compute the expected
position from a DIFFERENT config constant / a different generated file than
whatever the generator itself used, so the test can't just be checking that
the generator agrees with itself).
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

from faxbox import config as c
from faxbox.generate_drawers import BODY_INTERIOR_HEIGHT, BODY_INTERIOR_WIDTH

import svg_utils as su

pytestmark = [pytest.mark.usefixtures("regenerate_svgs")]

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "output"
SHELL_SVG = OUTPUT_DIR / "outer_shell.svg"
DRAWER_SVG = OUTPUT_DIR / "drawer.svg"

T = c.MATERIAL_THICKNESS


def _piece(svg_path, *synonyms):
    pieces = su.design_pieces(svg_path)
    found = su.find_piece_by_label(pieces, *synonyms)
    assert found is not None, (
        f"no piece labeled like {synonyms!r} found in {svg_path.name}; "
        f"labels present: {[p.label for p in pieces]}"
    )
    return found


def _blue_holes(piece):
    return [h for h in piece.holes if su.normalize_color(h.stroke) == "blue"]


# =============================================================================
# Standalone hardware/coupon fixtures (independent of the shell/drawer/lid
# pipeline -- generated by faxbox.generate_hardware / faxbox.calibration,
# never nested onto a sheet_*.svg, same pattern as test_layout.py's
# kerf_coupon_svg fixture).
# =============================================================================

@pytest.fixture(scope="session")
def hardware_svg():
    subprocess.run(
        [sys.executable, "-m", "faxbox.generate_hardware"],
        check=True, cwd=REPO_ROOT, capture_output=True,
    )
    path = OUTPUT_DIR / "hardware.svg"
    assert path.exists(), "faxbox.generate_hardware did not produce output/hardware.svg"
    return path


@pytest.fixture(scope="session")
def magnet_coupon_svg():
    subprocess.run(
        [sys.executable, "-m", "faxbox.calibration"],
        check=True, cwd=REPO_ROOT, capture_output=True,
    )
    path = OUTPUT_DIR / "magnet_coupon.svg"
    assert path.exists(), "faxbox.calibration did not produce output/magnet_coupon.svg"
    return path


# =============================================================================
# A. Drawer retention magnets: existence + size
# =============================================================================
# self.hole() burn-compensates like every other hole in this project (see
# config.py's "Drawer retention" comment and calibration.py's gridfinitybase
# citation): the drawn tool path is nominal - 2*BURN, same relationship
# test_layout.py's test_kerf_coupon_slot_widths_match_burn_compensated_nominal
# already encodes for the kerf coupon's own slots.
EXPECTED_MAGNET_DRAWN_DIA = c.MAGNET_HOLE_DIA - 2 * c.BURN


def _magnet_holes(piece):
    return [
        h for h in _blue_holes(piece)
        if h.bbox.dims_match(EXPECTED_MAGNET_DRAWN_DIA, EXPECTED_MAGNET_DRAWN_DIA, tol=0.1)
    ]


def test_divider_has_two_magnet_holes():
    piece = _piece(SHELL_SVG, "vertical divider", "divider")
    holes = _magnet_holes(piece)
    assert len(holes) == 2, (
        f"expected 2 magnet holes on the divider (one per drawer, coaxial with "
        f"each drawer's Back-wall hole), found {len(holes)}"
    )


def test_drawer_back_has_one_magnet_hole():
    piece = _piece(DRAWER_SVG, "back")
    holes = _magnet_holes(piece)
    assert len(holes) == 1, (
        f"expected 1 magnet hole on the drawer's LEADING wall (Back, opposite "
        f"the faceplate), found {len(holes)}"
    )


def test_drawer_front_has_no_magnet_hole():
    """Sanity: the magnet belongs on the leading wall (Back), not the
    faceplate/grip-slot end (Front) -- guards against the hole ending up on
    the wrong panel."""
    piece = _piece(DRAWER_SVG, "front")
    assert _magnet_holes(piece) == []


# =============================================================================
# A2. Coaxiality at closed position, via INDEPENDENT datums
# =============================================================================
# Anchor conventions (established elsewhere in this suite -- see
# test_svg_geometry.py's own module-level comment on frame mapping):
#   - Divider: captive ("ffff") on all 4 edges, so every edge's fingers
#     protrude T beyond the nominal blank -- bbox.xmin = box Y=0,
#     bbox.ymax = box Z = FLOOR_TOP - T (same relationship
#     test_bottom_panel_divider_row_position / test_divider_shelf_row_position
#     already rely on for the divider's OTHER hole row).
#   - Drawer Back panel: left/right edges finger ("F"), so bbox.xmin
#     extends T beyond nominal local x=0; top edge is plain/open (no
#     protrusion), so bbox.ymin IS the true, unextended top edge with no
#     correction (same relationship the grip-slot formula on Front relies on
#     -- DESIGN.md's slot spans 30.5->45.5 of the 53.5 height, cross-checked
#     in this project's own commit history).
#
# The cross-check below deliberately does NOT reuse config.MAGNET_BOX_Y /
# MAGNET_BOTTOM_DRAWER_Z / MAGNET_TOP_DRAWER_Z (the constants the *generators*
# both import) as the expected value. Instead it re-derives the drawer's
# closed-position offsets from the MEASURED drawer hole (whatever offset the
# drawer generator actually used) and an INDEPENDENT box-Y-center / box-Z
# datum taken from the rear wall's own already-defined opening constants
# (SHELL_EXT, BOTTOM_OPENING_Z0, TOP_OPENING_Z0) -- a real cross-check that
# would catch e.g. MAGNET_Y_OFFSET being applied inconsistently between
# shell_generator.py and generate_drawers.py, even though both currently
# import the same config constant.

def _divider_box_y(divider, hole):
    cx = (hole.bbox.xmin + hole.bbox.xmax) / 2
    return cx - divider.bbox.xmin


def _divider_box_z(divider, hole):
    cy = (hole.bbox.ymin + hole.bbox.ymax) / 2
    return (c.FLOOR_TOP - T) + (divider.bbox.ymax - cy)


def _back_offset_from_center(back, hole):
    """Drawer Back-wall magnet hole's X offset from the panel's own
    Y-center (box Y once installed), measured off the SVG (not assumed)."""
    cx = (hole.bbox.xmin + hole.bbox.xmax) / 2
    local_nominal_x = (cx - back.bbox.xmin) - T
    return local_nominal_x - BODY_INTERIOR_WIDTH / 2


def _back_mid_height_from_top(back, hole):
    """Drawer Back-wall magnet hole's distance below the panel's own
    (unextended, plain) top edge -- "drawer mid-height" measured from a
    clean anchor, not assumed."""
    cy = (hole.bbox.ymin + hole.bbox.ymax) / 2
    return cy - back.bbox.ymin


def test_magnet_holes_coaxial_at_closed_position():
    divider = _piece(SHELL_SVG, "vertical divider", "divider")
    back = _piece(DRAWER_SVG, "back")

    div_holes = _magnet_holes(divider)
    back_holes = _magnet_holes(back)
    assert len(div_holes) == 2 and len(back_holes) == 1
    back_hole = back_holes[0]

    offset_from_center = _back_offset_from_center(back, back_hole)
    mid_height_from_top = _back_mid_height_from_top(back, back_hole)

    # INDEPENDENT box-Y datum: the box's own exterior width (0 -> SHELL_EXT
    # width), not the T + INTERIOR_WIDTH/2 formula config.MAGNET_BOX_Y uses.
    expected_box_y = (0.0 + c.SHELL_EXT["width"]) / 2 + offset_from_center

    # INDEPENDENT box-Z datums: the rear wall's own sill-free opening
    # constants, not FLOOR_TOP/SHELF_Z1 (config.MAGNET_BOTTOM_DRAWER_Z /
    # MAGNET_TOP_DRAWER_Z's own inputs) directly.
    expected_z_by_span = {
        c.BOTTOM_OPENING_Z0 + mid_height_from_top: "bottom drawer",
        c.TOP_OPENING_Z0 + mid_height_from_top: "top drawer",
    }

    remaining = dict(expected_z_by_span)
    for hole in div_holes:
        measured_y = _divider_box_y(divider, hole)
        assert abs(measured_y - expected_box_y) <= 0.6, (
            f"divider magnet hole box Y={measured_y:.2f}, expected {expected_box_y:.2f} "
            f"(independent datum: SHELL_EXT width/2 + measured drawer offset)"
        )
        measured_z = _divider_box_z(divider, hole)
        best = min(remaining, key=lambda z: abs(measured_z - z))
        assert abs(measured_z - best) <= 0.6, (
            f"divider magnet hole box Z={measured_z:.2f} matches no expected drawer "
            f"mid-height (candidates: {remaining})"
        )
        del remaining[best]

    assert not remaining, f"no divider hole matched: {remaining}"


# =============================================================================
# A3. Clearances (literal mm, derived from config -- not hand-waved)
# =============================================================================

MIN_CLEARANCE = 3.0
DIVIDER_STRUCTURAL_CLEARANCE = 8.0


def test_divider_magnet_holes_clear_edges_and_shelf_line():
    divider = _piece(SHELL_SVG, "vertical divider", "divider")
    holes = _magnet_holes(divider)
    assert len(holes) == 2
    r = EXPECTED_MAGNET_DRAWN_DIA / 2

    shelf_rows = su.hole_line_rows(_blue_holes(divider), T, axis="x")
    bay_hits = [row for row in shelf_rows if row.span > 0.75 * c.INTERIOR_WIDTH]
    assert len(bay_hits) == 1, "expected the divider's own shelf finger-hole row"
    shelf_row = bay_hits[0]

    for hole in holes:
        cx = (hole.bbox.xmin + hole.bbox.xmax) / 2
        cy = (hole.bbox.ymin + hole.bbox.ymax) / 2

        left_clear = (cx - r) - divider.bbox.xmin
        right_clear = divider.bbox.xmax - (cx + r)
        top_clear = (cy - r) - divider.bbox.ymin
        bottom_clear = divider.bbox.ymax - (cy + r)
        assert min(left_clear, right_clear) >= DIVIDER_STRUCTURAL_CLEARANCE, (
            f"divider magnet hole too close to a Y edge: left={left_clear:.2f}, "
            f"right={right_clear:.2f} (need >= {DIVIDER_STRUCTURAL_CLEARANCE})"
        )
        assert min(top_clear, bottom_clear) >= DIVIDER_STRUCTURAL_CLEARANCE, (
            f"divider magnet hole too close to a Z edge: top={top_clear:.2f}, "
            f"bottom={bottom_clear:.2f} (need >= {DIVIDER_STRUCTURAL_CLEARANCE})"
        )

        # shelf_row.center is the row's cross-axis position (its own band
        # of holes is T tall, centered there); subtract both half-bands to
        # get true edge-to-edge clearance.
        cross_gap = abs(cy - shelf_row.center) - T / 2 - r
        assert cross_gap >= DIVIDER_STRUCTURAL_CLEARANCE, (
            f"divider magnet hole only {cross_gap:.2f}mm from the shelf finger-hole "
            f"row (need >= {DIVIDER_STRUCTURAL_CLEARANCE})"
        )

    cy0, cy1 = [(h.bbox.ymin + h.bbox.ymax) / 2 for h in holes]
    assert abs(cy0 - cy1) - 2 * r >= MIN_CLEARANCE, "the two divider magnet holes are too close together"


def test_drawer_back_magnet_hole_clears_edges():
    back = _piece(DRAWER_SVG, "back")
    holes = _magnet_holes(back)
    assert len(holes) == 1
    hole = holes[0]
    r = EXPECTED_MAGNET_DRAWN_DIA / 2
    cx = (hole.bbox.xmin + hole.bbox.xmax) / 2
    cy = (hole.bbox.ymin + hole.bbox.ymax) / 2

    left_clear = (cx - r) - back.bbox.xmin
    right_clear = back.bbox.xmax - (cx + r)
    top_clear = (cy - r) - back.bbox.ymin
    bottom_clear = back.bbox.ymax - (cy + r)
    assert min(left_clear, right_clear) >= MIN_CLEARANCE, (
        f"drawer Back magnet hole too close to a finger-jointed side edge: "
        f"left={left_clear:.2f}, right={right_clear:.2f}"
    )
    assert min(top_clear, bottom_clear) >= MIN_CLEARANCE, (
        f"drawer Back magnet hole too close to the top/bottom edge: "
        f"top={top_clear:.2f}, bottom={bottom_clear:.2f}"
    )


# =============================================================================
# B. Turn-button pivot hole: FRONT WALL only (REV.B, adversarial-review
# finding #1). REV.A put a pivot + paddle on each side wall; that mechanism
# was proven geometrically incapable of retention (the paddle's sweep plane
# and the lid's travel band never intersect -- see config.py's "Lid
# retention (iteration 2 REV.B...)" comment for the disjoint-volume proof)
# and was replaced, before any part was cut, with a single pivot on the
# FRONT WALL's exterior face, positioned so the paddle sweeps directly
# across the lid's own exit cross-section.
# =============================================================================

EXPECTED_PIVOT_DRAWN_DIA = c.TURN_BUTTON["pivot_hole_dia"] - 2 * c.BURN


def _pivot_holes(piece):
    return [
        h for h in _blue_holes(piece)
        if h.bbox.dims_match(EXPECTED_PIVOT_DRAWN_DIA, EXPECTED_PIVOT_DRAWN_DIA, tol=0.1)
    ]


# --- B1. Existence + regression guard: exactly one pivot hole, and it's on
# the front wall ONLY -- REV.A's side-wall pivot holes must never come back.

def test_front_wall_has_one_pivot_hole():
    wall = _piece(SHELL_SVG, "front wall")
    holes = _pivot_holes(wall)
    assert len(holes) == 1, f"expected 1 turn-button pivot hole on the front wall, found {len(holes)}"


@pytest.mark.parametrize("side", ["left wall", "right wall"])
def test_side_walls_have_zero_pivot_holes(side):
    """Regression guard for adversarial-review finding #1: REV.A drilled a
    pivot hole into each side wall for a mechanism that could never have
    retained the lid (disjoint sweep/travel volumes -- see config.py). If a
    future change reintroduces a side-wall pivot hole, this must fail."""
    wall = _piece(SHELL_SVG, side)
    holes = _pivot_holes(wall)
    assert holes == [], (
        f"{side}: expected ZERO turn-button pivot holes (REV.B moved the sole "
        f"pivot to the front wall), found {len(holes)}"
    )


def test_exactly_one_pivot_hole_across_whole_shell():
    """Sum across all 8 shell pieces: exactly 1 pivot hole total (front
    wall), not 2 (the old REV.A side-wall pair) or 0 (dropped entirely)."""
    total = sum(len(_pivot_holes(p)) for p in su.design_pieces(SHELL_SVG))
    assert total == 1, f"expected exactly 1 turn-button pivot hole shell-wide, found {total}"


# --- B2. Side walls are byte-identical to `main` (v1, pre-REV.A/REV.B): the
# fix for finding #1 must not have touched anything else on the side walls
# -- literally diff the regenerated side-wall geometry against `main`'s own
# generated output, not just eyeball the source diff.

@pytest.fixture(scope="session")
def main_shell_svg(tmp_path_factory):
    """Regenerate `main`'s outer_shell.svg from the actual `main`-branch
    source (via `git show`), in an isolated temp tree, so the comparison
    below is against real generated output -- not a hand-copied assumption
    about what v1 looked like."""
    tmp_root = tmp_path_factory.mktemp("main_shell")
    src_dir = tmp_root / "src" / "faxbox"
    src_dir.mkdir(parents=True)

    # svglabels.py joined shell_generator's imports in the 2026-07-09 QA
    # pass; the fixture must mirror main's actual import closure or the
    # subprocess dies on ModuleNotFoundError instead of generating.
    for name in ("__init__.py", "config.py", "shell_generator.py", "svglabels.py"):
        result = subprocess.run(
            ["git", "show", f"main:src/faxbox/{name}"],
            check=True, cwd=REPO_ROOT, capture_output=True, text=True,
        )
        (src_dir / name).write_text(result.stdout)

    env = dict(os.environ)
    env["PYTHONPATH"] = str(tmp_root / "src") + (
        (os.pathsep + env["PYTHONPATH"]) if env.get("PYTHONPATH") else ""
    )
    subprocess.run(
        [sys.executable, "-m", "faxbox.shell_generator"],
        check=True, cwd=tmp_root, capture_output=True, env=env,
    )
    path = tmp_root / "output" / "outer_shell.svg"
    assert path.exists(), "failed to regenerate main's outer_shell.svg for comparison"
    return path


def _path_signature(p):
    """A path's own geometry, independent of draw order: rounded bbox +
    stroke color (ignores label text, which can legitimately differ)."""
    b = p.bbox
    return (
        su.normalize_color(p.stroke),
        round(b.xmin, 3), round(b.xmax, 3), round(b.ymin, 3), round(b.ymax, 3),
    )


@pytest.mark.parametrize("side", ["left wall", "right wall"])
def test_side_wall_matches_main_footprint(main_shell_svg, side):
    """Every CUT path (outer boundary + every blue hole) on this side wall
    must have an exact counterpart in `main`'s own generated side wall --
    i.e. REV.B's fix (deleting the side-wall pivot-hole callback) did not
    change anything else about the side walls' cut geometry. A stray
    leftover pivot hole, a shifted finger-hole row, or any other regression
    would show up as a mismatched signature set.

    Scoped to CUT (blue) paths since 2026-07-10: the right wall's red
    "FAX MACHINE" engraving was removed by Ben's decision (issue #25
    open-item 1), so the engrave layer legitimately differs from a `main`
    that predates the removal. Walls must currently carry NO red at all
    (asserted here and in test_engrave_cut_clearance) until art-integration
    lands its reviewed engrave layers."""
    main_piece = _piece(main_shell_svg, side)
    cur_piece = _piece(SHELL_SVG, side)

    def cut_sigs(piece):
        return sorted(
            _path_signature(p) for p in piece.all_paths()
            if su.normalize_color(p.stroke) == "blue"
        )

    main_sigs = cut_sigs(main_piece)
    cur_sigs = cut_sigs(cur_piece)

    assert len(cur_sigs) == len(main_sigs), (
        f"{side}: cut path count changed vs. main: main={len(main_sigs)}, current={len(cur_sigs)}"
    )
    assert cur_sigs == main_sigs, (
        f"{side}: cut geometry differs from main's v1 output -- REV.B must "
        f"leave the side walls' cut layer byte-identical to v1"
    )

    cur_red = [p for p in cur_piece.all_paths() if su.normalize_color(p.stroke) == "red"]
    assert not cur_red, (
        f"{side}: unexpected red engrave paths (pixel text was removed "
        f"2026-07-10; art arrives only via the art-integration pipeline)"
    )


# --- B3. Front-wall pivot position, from INDEPENDENT datums (the wall's own
# bottom finger-hole row as the X/Y calibration anchor, and the wall's own
# unextended Z axis -- neither imported from the TURN_BUTTON_PIVOT_BOX_*
# constants the generator itself used).

def _front_wall_bottom_row(wall):
    """The front wall's bottom-panel finger-hole row spans local x
    0..INTERIOR_WIDTH (box Y T..T+INTERIOR_WIDTH) -- an independent anchor
    for mapping measured SVG x back to box Y, distinct from the pivot hole
    itself."""
    rows = su.hole_line_rows(_blue_holes(wall), T, axis="x")
    hits = [r for r in rows if r.span > 0.9 * c.INTERIOR_WIDTH]
    assert len(hits) == 1, "expected the front wall's own bottom-panel finger-hole row"
    return hits[0]


def _front_wall_to_box_y(wall):
    row = _front_wall_bottom_row(wall)
    scale = c.INTERIOR_WIDTH / (row.hi - row.lo)
    return lambda x: T + (x - row.lo) * scale


def _front_wall_box_z(wall, y):
    """Front wall's Z axis is unextended (0 jointed edges -- see
    test_front_wall_blank_size), so its bbox top/bottom map straight to box
    Z=FRONT_WALL_HEIGHT/0 with no correction."""
    return c.FRONT_WALL_HEIGHT - (y - wall.bbox.ymin)


def test_front_wall_pivot_hole_position():
    wall = _piece(SHELL_SVG, "front wall")
    to_box_y = _front_wall_to_box_y(wall)
    holes = _pivot_holes(wall)
    assert len(holes) == 1
    hole = holes[0]
    cx = (hole.bbox.xmin + hole.bbox.xmax) / 2
    cy = (hole.bbox.ymin + hole.bbox.ymax) / 2
    box_y = to_box_y(cx)
    box_z = _front_wall_box_z(wall, cy)
    assert abs(box_y - c.TURN_BUTTON_PIVOT_BOX_Y) <= 0.6, (
        f"front wall: pivot hole box Y={box_y:.2f}, expected {c.TURN_BUTTON_PIVOT_BOX_Y}"
    )
    assert abs(box_z - c.TURN_BUTTON_PIVOT_BOX_Z) <= 0.6, (
        f"front wall: pivot hole box Z={box_z:.2f}, expected {c.TURN_BUTTON_PIVOT_BOX_Z}"
    )
    # Literal clearances (DESIGN.md): >=3mm from either vertical (side-wall)
    # joint zone and below the wall's own plain top edge.
    assert box_y - T >= MIN_CLEARANCE, (
        f"front wall: pivot hole only {box_y - T:.2f}mm past the left joint zone (need >= 3mm)"
    )
    assert (c.SHELL_EXT["width"] - T) - box_y >= MIN_CLEARANCE, (
        f"front wall: pivot hole only {(c.SHELL_EXT['width'] - T) - box_y:.2f}mm past the "
        f"right joint zone (need >= 3mm)"
    )
    assert c.FRONT_WALL_TOP - box_z >= MIN_CLEARANCE, (
        f"front wall: pivot hole only {c.FRONT_WALL_TOP - box_z:.2f}mm below the wall's top edge "
        f"(need >= 3mm)"
    )


# --- B4. THE BLOCKING TEST. This is the assertion whose absence let REV.A
# ship: it does not just check "a pivot hole exists at the documented spot"
# (B3 above already does that) -- it independently computes whether the
# button, rotated up, actually GEOMETRICALLY OVERLAPS the lid's own exit
# cross-section, in both Y and Z, with real margin. Moving the pivot to a
# non-blocking Z, shrinking the paddle so its measured reach is too short,
# or re-siting the whole mechanism onto a wall the lid doesn't cross would
# all make this fail -- unlike a purely positional check, which would have
# happily passed for REV.A's side-wall pivot too.

def _measured_button_reach(piece):
    """Real pivot-to-tip distance, measured from the actual drawn hardware
    piece (not assumed from the TURN_BUTTON config dict)."""
    holes = [
        h for h in piece.holes
        if h.bbox.dims_match(EXPECTED_PIVOT_DRAWN_DIA, EXPECTED_PIVOT_DRAWN_DIA, tol=0.1)
    ]
    assert len(holes) == 1
    hole = holes[0]
    pivot_x = (hole.bbox.xmin + hole.bbox.xmax) / 2
    return max(abs(pivot_x - piece.bbox.xmin), abs(piece.bbox.xmax - pivot_x))


def _measured_button_cap_radius(piece):
    """Half the piece's own measured cross-axis (Y) width -- the paddle's
    blunt-end cap radius, i.e. how far it spans off the pivot's own
    coordinate when rotated to point straight along its axis."""
    return piece.bbox.height / 2


BLOCKING_MARGIN = 1.0


def test_button_up_envelope_blocks_lid_exit(hardware_svg):
    """Independent datums, per DESIGN.md's explicit call for this test:
    - lid Y-span: SHELL_EXT width and SLIDE_CLEARANCE (not SLIDING_LID,
      which is the same constant generate_lids.py itself consumes).
    - lid Z-band: LID_SLOT_BOTTOM (slot floor the lid rests on under
      gravity) .. + T (the lid's own thickness) -- not LID_SLOT_TOP, which
      includes the slot's extra vertical *clearance* above the lid, not
      lid material itself.
    - button pivot: config's TURN_BUTTON_PIVOT_BOX_Y/Z (cross-checked
      against the actual cut hole position by test_front_wall_pivot_hole_
      position above) plus the MEASURED reach/width of the actual drawn
      hardware piece (not the TURN_BUTTON dict the generator used).
    """
    pieces = su.design_pieces(hardware_svg)
    assert len(pieces) == 1
    button = pieces[0]
    reach = _measured_button_reach(button)
    cap_radius = _measured_button_cap_radius(button)

    # Independent lid Y-span (box Y).
    lid_width = c.SHELL_EXT["width"] - c.SLIDE_CLEARANCE
    lid_y0 = (c.SHELL_EXT["width"] - lid_width) / 2
    lid_y1 = lid_y0 + lid_width

    # Independent lid Z-band (box Z): the lid's own physical thickness,
    # resting on the slot floor.
    lid_z0 = c.LID_SLOT_BOTTOM
    lid_z1 = lid_z0 + T

    # Button-up envelope (rotated so its long axis points toward +Z): Y
    # spans +-cap_radius around the pivot; Z spans from (pivot - cap_radius)
    # -- the blunt cap's rear -- up to (pivot + reach) -- the tip.
    pivot_y = c.TURN_BUTTON_PIVOT_BOX_Y
    pivot_z = c.TURN_BUTTON_PIVOT_BOX_Z
    button_y0, button_y1 = pivot_y - cap_radius, pivot_y + cap_radius
    button_z0, button_z1 = pivot_z - cap_radius, pivot_z + reach

    y_margin = min(button_y1, lid_y1) - max(button_y0, lid_y0)
    z_margin = min(button_z1, lid_z1) - max(button_z0, lid_z0)

    assert y_margin >= BLOCKING_MARGIN, (
        f"button-up envelope Y=[{button_y0:.2f},{button_y1:.2f}] overlaps the lid's "
        f"Y=[{lid_y0:.2f},{lid_y1:.2f}] exit span by only {y_margin:.2f}mm "
        f"(need >= {BLOCKING_MARGIN}mm) -- the button would not reliably block the lid"
    )
    assert z_margin >= BLOCKING_MARGIN, (
        f"button-up envelope Z=[{button_z0:.2f},{button_z1:.2f}] overlaps the lid's "
        f"Z=[{lid_z0:.2f},{lid_z1:.2f}] exit band by only {z_margin:.2f}mm "
        f"(need >= {BLOCKING_MARGIN}mm) -- the button would not reliably block the lid"
    )


def test_button_down_clears_lid_travel(hardware_svg):
    """Rotated fully DOWN (180 deg from the up/blocking orientation), the
    whole paddle must sit below the front wall's own top edge
    (FRONT_WALL_TOP) so the lid can slide freely when the button is
    disengaged -- with a real (not zero) clearance margin."""
    pieces = su.design_pieces(hardware_svg)
    assert len(pieces) == 1
    button = pieces[0]
    cap_radius = _measured_button_cap_radius(button)

    pivot_z = c.TURN_BUTTON_PIVOT_BOX_Z
    button_down_top_z = pivot_z + cap_radius  # blunt cap, now the near/top end
    clearance = c.FRONT_WALL_TOP - button_down_top_z
    assert clearance >= BLOCKING_MARGIN, (
        f"button rotated down reaches box Z={button_down_top_z:.2f}, only "
        f"{clearance:.2f}mm below FRONT_WALL_TOP={c.FRONT_WALL_TOP} "
        f"(need >= {BLOCKING_MARGIN}mm so the lid slides freely when disengaged)"
    )


# =============================================================================
# C. Turn-button hardware piece(s)
# =============================================================================
# REV.B (adversarial-review finding #1): ONE button now, not two -- the
# side-wall mechanism (2 pieces) was replaced by a single front-wall button.

def test_hardware_has_one_button_piece(hardware_svg):
    pieces = su.design_pieces(hardware_svg)
    assert len(pieces) == 1, f"expected 1 turn-button piece (REV.B), found {len(pieces)}"
    assert len(pieces[0].holes) == 1, f"{pieces[0].label!r} should carry exactly its own pivot hole"


def test_button_pivot_hole_present_and_sized(hardware_svg):
    for piece in su.design_pieces(hardware_svg):
        holes = [
            h for h in piece.holes
            if h.bbox.dims_match(EXPECTED_PIVOT_DRAWN_DIA, EXPECTED_PIVOT_DRAWN_DIA, tol=0.1)
        ]
        assert len(holes) == 1, f"{piece.label!r} missing its Ø{c.TURN_BUTTON['pivot_hole_dia']}mm pivot hole"


def test_button_reach_is_sufficient(hardware_svg):
    """Measured tip-to-pivot distance must be >= (LID_FRONT_BAND_Z1 + 1) -
    TURN_BUTTON_PIVOT_BOX_Z (DESIGN.md: rotated to vertical, the tip must
    clear the lid band's top by >= 1mm). This is a simpler, narrower check
    than test_button_up_envelope_blocks_lid_exit above (1-D reach only, no
    Y-span or independent-datum cross-check) -- kept as a focused regression
    guard on the reach number alone."""
    required_reach = (c.LID_FRONT_BAND_Z1 + 1.0) - c.TURN_BUTTON_PIVOT_BOX_Z
    for piece in su.design_pieces(hardware_svg):
        reach = _measured_button_reach(piece)
        assert reach >= required_reach, (
            f"{piece.label!r}: measured reach {reach:.2f}mm < required {required_reach:.2f}mm"
        )


def test_buttons_do_not_overlap_in_nest(hardware_svg):
    pieces = su.get_pieces(hardware_svg)
    for i in range(len(pieces)):
        for j in range(i + 1, len(pieces)):
            assert not pieces[i].bbox.overlaps(pieces[j].bbox), (
                f"{pieces[i].label!r} overlaps {pieces[j].label!r} in {hardware_svg.name}"
            )


# =============================================================================
# D. Magnet press-fit coupon
# =============================================================================

def test_magnet_coupon_has_one_piece_and_four_holes(magnet_coupon_svg):
    pieces = su.get_pieces(magnet_coupon_svg)
    assert len(pieces) == 1
    assert len(pieces[0].holes) == 4


def test_magnet_coupon_hole_diameters(magnet_coupon_svg):
    """Adversarial-review finding #3: the coupon's gauge holes must be
    burn-COMPENSATED the same way the real part holes (divider/drawer Back)
    are -- NOT burn-neutral like the kerf square. A burn-neutral gauge
    labeled 5.65mm would cut out at physical 5.65 + 2*BURN (~5.81mm at
    BURN=0.08), a different physical size than a same-labeled PART hole
    (which is burn-compensated: drawn at 5.65 - 2*BURN, cuts out at
    physical 5.65) -- silently eating ~46% of the 0.35mm press-fit budget
    before a magnet is ever pressed in. Do NOT touch the kerf square in
    test_layout.py: that one measures the kerf itself and must stay
    burn-neutral -- this distinction is the whole point of finding #3."""
    from faxbox import calibration as cal

    piece = su.get_pieces(magnet_coupon_svg)[0]
    holes = sorted(piece.holes, key=lambda h: h.bbox.xmin)
    assert len(cal.MAGNET_COUPON_DIAMETERS) == 4
    for hole, nominal in zip(holes, cal.MAGNET_COUPON_DIAMETERS):
        expected_drawn = nominal - 2 * c.BURN
        assert abs(hole.bbox.width - expected_drawn) <= 0.05, (
            f"magnet coupon hole labeled {nominal}mm measured {hole.bbox.width:.3f}mm, "
            f"expected burn-COMPENSATED drawn size {expected_drawn:.3f}mm (label - 2*BURN)"
        )
    assert min(cal.MAGNET_COUPON_DIAMETERS) < c.MAGNET_HOLE_DIA < max(cal.MAGNET_COUPON_DIAMETERS), (
        "coupon should span the current MAGNET_HOLE_DIA guess"
    )


def test_magnet_coupon_matches_part_hole_for_nominal_gauge(magnet_coupon_svg):
    """Cross-check (finding #3): the coupon's gauge hole labeled exactly
    MAGNET_HOLE_DIA (5.65mm, the current config guess) must measure the
    IDENTICAL drawn diameter as the real divider/drawer magnet holes
    (EXPECTED_MAGNET_DRAWN_DIA, defined in section A above from the SAME
    self.hole()-burn-compensation relationship) -- proving the coupon and
    the real parts now share one code path, not two diverging ones."""
    from faxbox import calibration as cal

    piece = su.get_pieces(magnet_coupon_svg)[0]
    holes = sorted(piece.holes, key=lambda h: h.bbox.xmin)
    nominal_index = cal.MAGNET_COUPON_DIAMETERS.index(c.MAGNET_HOLE_DIA)
    nominal_hole = holes[nominal_index]
    assert abs(nominal_hole.bbox.width - EXPECTED_MAGNET_DRAWN_DIA) <= 0.05, (
        f"coupon's {c.MAGNET_HOLE_DIA}mm gauge hole measures {nominal_hole.bbox.width:.3f}mm, "
        f"but the real part hole of the same label measures {EXPECTED_MAGNET_DRAWN_DIA:.3f}mm -- "
        f"the coupon no longer matches what the part actually gets"
    )


def test_magnet_coupon_all_strokes_blue(magnet_coupon_svg):
    for p in su.iter_paths(magnet_coupon_svg):
        assert su.normalize_color(p.stroke) == "blue", (
            f"magnet coupon has a non-blue stroke: {p.stroke!r} (nothing on it is engraved)"
        )
