"""Tests for iteration-2 retention (DESIGN.md "Retention (iteration 2,
magnets + turn-buttons)", issue #20): the drawer magnet-pair holes (drawer
Back wall <-> divider), the side-wall turn-button pivot holes, the turn-
button hardware pieces, and the magnet press-fit coupon.

Style follows test_svg_geometry.py: parse the real SVGs with
tests/svg_utils.py, existence-first, literal bounds -- and, for the
positional checks, an independent-datum cross-check (compute the expected
position from a DIFFERENT config constant / a different generated file than
whatever the generator itself used, so the test can't just be checking that
the generator agrees with itself).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from faxbox import config as c
from faxbox.generate_drawers import BODY_INTERIOR_HEIGHT, BODY_INTERIOR_WIDTH

import svg_utils as su

pytestmark = [pytest.mark.usefixtures("regenerate_svgs")]

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "output"
SHELL_SVG = OUTPUT_DIR / "outer_shell.svg"
DRAWER_SVG = OUTPUT_DIR / "drawer.svg"

T = c.MATERIAL_THICKNESS


def _piece(svg_path, *synonyms):
    pieces = su.design_pieces(svg_path)
    found = su.find_piece_by_label(pieces, *synonyms)
    assert found is not None, (
        f"no piece labeled like {synonyms!r} found in {svg_path.name}; "
        f"labels present: {[p.label for p in pieces]}"
    )
    return found


def _blue_holes(piece):
    return [h for h in piece.holes if su.normalize_color(h.stroke) == "blue"]


# =============================================================================
# Standalone hardware/coupon fixtures (independent of the shell/drawer/lid
# pipeline -- generated by faxbox.generate_hardware / faxbox.calibration,
# never nested onto a sheet_*.svg, same pattern as test_layout.py's
# kerf_coupon_svg fixture).
# =============================================================================

@pytest.fixture(scope="session")
def hardware_svg():
    subprocess.run(
        [sys.executable, "-m", "faxbox.generate_hardware"],
        check=True, cwd=REPO_ROOT, capture_output=True,
    )
    path = OUTPUT_DIR / "hardware.svg"
    assert path.exists(), "faxbox.generate_hardware did not produce output/hardware.svg"
    return path


@pytest.fixture(scope="session")
def magnet_coupon_svg():
    subprocess.run(
        [sys.executable, "-m", "faxbox.calibration"],
        check=True, cwd=REPO_ROOT, capture_output=True,
    )
    path = OUTPUT_DIR / "magnet_coupon.svg"
    assert path.exists(), "faxbox.calibration did not produce output/magnet_coupon.svg"
    return path


# =============================================================================
# A. Drawer retention magnets: existence + size
# =============================================================================
# self.hole() burn-compensates like every other hole in this project (see
# config.py's "Drawer retention" comment and calibration.py's gridfinitybase
# citation): the drawn tool path is nominal - 2*BURN, same relationship
# test_layout.py's test_kerf_coupon_slot_widths_match_burn_compensated_nominal
# already encodes for the kerf coupon's own slots.
EXPECTED_MAGNET_DRAWN_DIA = c.MAGNET_HOLE_DIA - 2 * c.BURN


def _magnet_holes(piece):
    return [
        h for h in _blue_holes(piece)
        if h.bbox.dims_match(EXPECTED_MAGNET_DRAWN_DIA, EXPECTED_MAGNET_DRAWN_DIA, tol=0.1)
    ]


def test_divider_has_two_magnet_holes():
    piece = _piece(SHELL_SVG, "vertical divider", "divider")
    holes = _magnet_holes(piece)
    assert len(holes) == 2, (
        f"expected 2 magnet holes on the divider (one per drawer, coaxial with "
        f"each drawer's Back-wall hole), found {len(holes)}"
    )


def test_drawer_back_has_one_magnet_hole():
    piece = _piece(DRAWER_SVG, "back")
    holes = _magnet_holes(piece)
    assert len(holes) == 1, (
        f"expected 1 magnet hole on the drawer's LEADING wall (Back, opposite "
        f"the faceplate), found {len(holes)}"
    )


def test_drawer_front_has_no_magnet_hole():
    """Sanity: the magnet belongs on the leading wall (Back), not the
    faceplate/grip-slot end (Front) -- guards against the hole ending up on
    the wrong panel."""
    piece = _piece(DRAWER_SVG, "front")
    assert _magnet_holes(piece) == []


# =============================================================================
# A2. Coaxiality at closed position, via INDEPENDENT datums
# =============================================================================
# Anchor conventions (established elsewhere in this suite -- see
# test_svg_geometry.py's own module-level comment on frame mapping):
#   - Divider: captive ("ffff") on all 4 edges, so every edge's fingers
#     protrude T beyond the nominal blank -- bbox.xmin = box Y=0,
#     bbox.ymax = box Z = FLOOR_TOP - T (same relationship
#     test_bottom_panel_divider_row_position / test_divider_shelf_row_position
#     already rely on for the divider's OTHER hole row).
#   - Drawer Back panel: left/right edges finger ("F"), so bbox.xmin
#     extends T beyond nominal local x=0; top edge is plain/open (no
#     protrusion), so bbox.ymin IS the true, unextended top edge with no
#     correction (same relationship the grip-slot formula on Front relies on
#     -- DESIGN.md's slot spans 30.5->45.5 of the 53.5 height, cross-checked
#     in this project's own commit history).
#
# The cross-check below deliberately does NOT reuse config.MAGNET_BOX_Y /
# MAGNET_BOTTOM_DRAWER_Z / MAGNET_TOP_DRAWER_Z (the constants the *generators*
# both import) as the expected value. Instead it re-derives the drawer's
# closed-position offsets from the MEASURED drawer hole (whatever offset the
# drawer generator actually used) and an INDEPENDENT box-Y-center / box-Z
# datum taken from the rear wall's own already-defined opening constants
# (SHELL_EXT, BOTTOM_OPENING_Z0, TOP_OPENING_Z0) -- a real cross-check that
# would catch e.g. MAGNET_Y_OFFSET being applied inconsistently between
# shell_generator.py and generate_drawers.py, even though both currently
# import the same config constant.

def _divider_box_y(divider, hole):
    cx = (hole.bbox.xmin + hole.bbox.xmax) / 2
    return cx - divider.bbox.xmin


def _divider_box_z(divider, hole):
    cy = (hole.bbox.ymin + hole.bbox.ymax) / 2
    return (c.FLOOR_TOP - T) + (divider.bbox.ymax - cy)


def _back_offset_from_center(back, hole):
    """Drawer Back-wall magnet hole's X offset from the panel's own
    Y-center (box Y once installed), measured off the SVG (not assumed)."""
    cx = (hole.bbox.xmin + hole.bbox.xmax) / 2
    local_nominal_x = (cx - back.bbox.xmin) - T
    return local_nominal_x - BODY_INTERIOR_WIDTH / 2


def _back_mid_height_from_top(back, hole):
    """Drawer Back-wall magnet hole's distance below the panel's own
    (unextended, plain) top edge -- "drawer mid-height" measured from a
    clean anchor, not assumed."""
    cy = (hole.bbox.ymin + hole.bbox.ymax) / 2
    return cy - back.bbox.ymin


def test_magnet_holes_coaxial_at_closed_position():
    divider = _piece(SHELL_SVG, "vertical divider", "divider")
    back = _piece(DRAWER_SVG, "back")

    div_holes = _magnet_holes(divider)
    back_holes = _magnet_holes(back)
    assert len(div_holes) == 2 and len(back_holes) == 1
    back_hole = back_holes[0]

    offset_from_center = _back_offset_from_center(back, back_hole)
    mid_height_from_top = _back_mid_height_from_top(back, back_hole)

    # INDEPENDENT box-Y datum: the box's own exterior width (0 -> SHELL_EXT
    # width), not the T + INTERIOR_WIDTH/2 formula config.MAGNET_BOX_Y uses.
    expected_box_y = (0.0 + c.SHELL_EXT["width"]) / 2 + offset_from_center

    # INDEPENDENT box-Z datums: the rear wall's own sill-free opening
    # constants, not FLOOR_TOP/SHELF_Z1 (config.MAGNET_BOTTOM_DRAWER_Z /
    # MAGNET_TOP_DRAWER_Z's own inputs) directly.
    expected_z_by_span = {
        c.BOTTOM_OPENING_Z0 + mid_height_from_top: "bottom drawer",
        c.TOP_OPENING_Z0 + mid_height_from_top: "top drawer",
    }

    remaining = dict(expected_z_by_span)
    for hole in div_holes:
        measured_y = _divider_box_y(divider, hole)
        assert abs(measured_y - expected_box_y) <= 0.6, (
            f"divider magnet hole box Y={measured_y:.2f}, expected {expected_box_y:.2f} "
            f"(independent datum: SHELL_EXT width/2 + measured drawer offset)"
        )
        measured_z = _divider_box_z(divider, hole)
        best = min(remaining, key=lambda z: abs(measured_z - z))
        assert abs(measured_z - best) <= 0.6, (
            f"divider magnet hole box Z={measured_z:.2f} matches no expected drawer "
            f"mid-height (candidates: {remaining})"
        )
        del remaining[best]

    assert not remaining, f"no divider hole matched: {remaining}"


# =============================================================================
# A3. Clearances (literal mm, derived from config -- not hand-waved)
# =============================================================================

MIN_CLEARANCE = 3.0
DIVIDER_STRUCTURAL_CLEARANCE = 8.0


def test_divider_magnet_holes_clear_edges_and_shelf_line():
    divider = _piece(SHELL_SVG, "vertical divider", "divider")
    holes = _magnet_holes(divider)
    assert len(holes) == 2
    r = EXPECTED_MAGNET_DRAWN_DIA / 2

    shelf_rows = su.hole_line_rows(_blue_holes(divider), T, axis="x")
    bay_hits = [row for row in shelf_rows if row.span > 0.75 * c.INTERIOR_WIDTH]
    assert len(bay_hits) == 1, "expected the divider's own shelf finger-hole row"
    shelf_row = bay_hits[0]

    for hole in holes:
        cx = (hole.bbox.xmin + hole.bbox.xmax) / 2
        cy = (hole.bbox.ymin + hole.bbox.ymax) / 2

        left_clear = (cx - r) - divider.bbox.xmin
        right_clear = divider.bbox.xmax - (cx + r)
        top_clear = (cy - r) - divider.bbox.ymin
        bottom_clear = divider.bbox.ymax - (cy + r)
        assert min(left_clear, right_clear) >= DIVIDER_STRUCTURAL_CLEARANCE, (
            f"divider magnet hole too close to a Y edge: left={left_clear:.2f}, "
            f"right={right_clear:.2f} (need >= {DIVIDER_STRUCTURAL_CLEARANCE})"
        )
        assert min(top_clear, bottom_clear) >= DIVIDER_STRUCTURAL_CLEARANCE, (
            f"divider magnet hole too close to a Z edge: top={top_clear:.2f}, "
            f"bottom={bottom_clear:.2f} (need >= {DIVIDER_STRUCTURAL_CLEARANCE})"
        )

        # shelf_row.center is the row's cross-axis position (its own band
        # of holes is T tall, centered there); subtract both half-bands to
        # get true edge-to-edge clearance.
        cross_gap = abs(cy - shelf_row.center) - T / 2 - r
        assert cross_gap >= DIVIDER_STRUCTURAL_CLEARANCE, (
            f"divider magnet hole only {cross_gap:.2f}mm from the shelf finger-hole "
            f"row (need >= {DIVIDER_STRUCTURAL_CLEARANCE})"
        )

    cy0, cy1 = [(h.bbox.ymin + h.bbox.ymax) / 2 for h in holes]
    assert abs(cy0 - cy1) - 2 * r >= MIN_CLEARANCE, "the two divider magnet holes are too close together"


def test_drawer_back_magnet_hole_clears_edges():
    back = _piece(DRAWER_SVG, "back")
    holes = _magnet_holes(back)
    assert len(holes) == 1
    hole = holes[0]
    r = EXPECTED_MAGNET_DRAWN_DIA / 2
    cx = (hole.bbox.xmin + hole.bbox.xmax) / 2
    cy = (hole.bbox.ymin + hole.bbox.ymax) / 2

    left_clear = (cx - r) - back.bbox.xmin
    right_clear = back.bbox.xmax - (cx + r)
    top_clear = (cy - r) - back.bbox.ymin
    bottom_clear = back.bbox.ymax - (cy + r)
    assert min(left_clear, right_clear) >= MIN_CLEARANCE, (
        f"drawer Back magnet hole too close to a finger-jointed side edge: "
        f"left={left_clear:.2f}, right={right_clear:.2f}"
    )
    assert min(top_clear, bottom_clear) >= MIN_CLEARANCE, (
        f"drawer Back magnet hole too close to the top/bottom edge: "
        f"top={top_clear:.2f}, bottom={bottom_clear:.2f}"
    )


# =============================================================================
# B. Turn-button pivot holes on the side walls
# =============================================================================

EXPECTED_PIVOT_DRAWN_DIA = c.TURN_BUTTON["pivot_hole_dia"] - 2 * c.BURN
WALL_SIDES = [("right wall", False), ("left wall", True)]


def _pivot_holes(piece):
    return [
        h for h in _blue_holes(piece)
        if h.bbox.dims_match(EXPECTED_PIVOT_DRAWN_DIA, EXPECTED_PIVOT_DRAWN_DIA, tol=0.1)
    ]


DIVIDER_LINE_NOMINAL = c.DIVIDER_HEIGHT
DIVIDER_MID_BOX_X = (c.DIVIDER_X0 + c.DIVIDER_X1) / 2


def _wall_divider_row(wall):
    """Same anchor as test_svg_geometry.py: the wall's own vertical divider
    finger-hole column, independently re-derived here rather than imported,
    so this test doesn't share code with the generator's existing coverage."""
    rows = su.hole_line_rows(_blue_holes(wall), T, axis="y")
    hits = [r for r in rows if 0.75 * DIVIDER_LINE_NOMINAL <= r.span <= DIVIDER_LINE_NOMINAL + 1.0]
    assert len(hits) == 1
    return hits[0]


def _wall_frame(wall, mirror):
    col = _wall_divider_row(wall).center
    sign = -1.0 if mirror else 1.0
    return lambda x: DIVIDER_MID_BOX_X + sign * (x - col)


def _wall_box_z(wall, y):
    return c.WALL_HEIGHT - (y - wall.bbox.ymin)


@pytest.mark.parametrize("side,mirror", WALL_SIDES)
def test_side_wall_has_one_pivot_hole(side, mirror):
    wall = _piece(SHELL_SVG, side)
    holes = _pivot_holes(wall)
    assert len(holes) == 1, f"expected 1 turn-button pivot hole on {side}, found {len(holes)}"


@pytest.mark.parametrize("side,mirror", WALL_SIDES)
def test_side_wall_pivot_hole_position(side, mirror):
    wall = _piece(SHELL_SVG, side)
    to_box_x = _wall_frame(wall, mirror)
    holes = _pivot_holes(wall)
    assert len(holes) == 1
    hole = holes[0]
    cx = (hole.bbox.xmin + hole.bbox.xmax) / 2
    cy = (hole.bbox.ymin + hole.bbox.ymax) / 2
    box_x = to_box_x(cx)
    box_z = _wall_box_z(wall, cy)
    assert abs(box_x - c.TURN_BUTTON_PIVOT_X) <= 0.6, (
        f"{side}: pivot hole box X={box_x:.2f}, expected {c.TURN_BUTTON_PIVOT_X}"
    )
    assert abs(box_z - c.TURN_BUTTON_PIVOT_Z) <= 0.6, (
        f"{side}: pivot hole box Z={box_z:.2f}, expected {c.TURN_BUTTON_PIVOT_Z}"
    )
    # Literal clearances (DESIGN.md): >=3mm past the front-edge finger-joint
    # zone (box X 0->T) and >=3mm below the slot floor.
    assert box_x - T >= MIN_CLEARANCE, (
        f"{side}: pivot hole only {box_x - T:.2f}mm past the front joint zone (need >= 3mm)"
    )
    assert c.LID_SLOT_BOTTOM - box_z >= MIN_CLEARANCE, (
        f"{side}: pivot hole only {c.LID_SLOT_BOTTOM - box_z:.2f}mm below the slot floor (need >= 3mm)"
    )


def test_side_wall_pivot_holes_are_true_mirrors():
    """Both walls' pivot holes must map to the SAME box (X, Z) once each
    wall's own mirror transform is applied -- otherwise the two buttons
    wouldn't sit at corresponding positions on the two walls."""
    positions = {}
    for side, mirror in WALL_SIDES:
        wall = _piece(SHELL_SVG, side)
        to_box_x = _wall_frame(wall, mirror)
        hole = _pivot_holes(wall)[0]
        cx = (hole.bbox.xmin + hole.bbox.xmax) / 2
        cy = (hole.bbox.ymin + hole.bbox.ymax) / 2
        positions[side] = (to_box_x(cx), _wall_box_z(wall, cy))

    (rx, rz), (lx, lz) = positions["right wall"], positions["left wall"]
    assert abs(rx - lx) <= 0.6, f"pivot holes not mirrored in X: right={rx:.2f}, left={lx:.2f}"
    assert abs(rz - lz) <= 0.6, f"pivot holes not mirrored in Z: right={rz:.2f}, left={lz:.2f}"


def test_pivot_hole_clear_of_engraving_zone():
    """DESIGN.md explicitly calls for this assertion even though the two
    features are far apart: engrave center (152.4, 63.5) vs pivot (8.0,
    112.0) on the right wall (the only wall carrying the engraving)."""
    wall = _piece(SHELL_SVG, "right wall")
    to_box_x = _wall_frame(wall, mirror=False)
    reds = [h for h in wall.holes if su.normalize_color(h.stroke) == "red"]
    assert reds, "expected red engraving paths on the right wall"
    xs = [p.bbox.xmin for p in reds] + [p.bbox.xmax for p in reds]
    ys = [p.bbox.ymin for p in reds] + [p.bbox.ymax for p in reds]
    engrave_x0, engrave_x1 = to_box_x(min(xs)), to_box_x(max(xs))
    engrave_z0, engrave_z1 = _wall_box_z(wall, max(ys)), _wall_box_z(wall, min(ys))

    pivot_x, pivot_z = c.TURN_BUTTON_PIVOT_X, c.TURN_BUTTON_PIVOT_Z
    outside_x = pivot_x < min(engrave_x0, engrave_x1) or pivot_x > max(engrave_x0, engrave_x1)
    outside_z = pivot_z < min(engrave_z0, engrave_z1) or pivot_z > max(engrave_z0, engrave_z1)
    assert outside_x or outside_z, (
        f"pivot hole ({pivot_x}, {pivot_z}) falls inside the engrave zone "
        f"X=[{engrave_x0:.1f},{engrave_x1:.1f}] Z=[{engrave_z0:.1f},{engrave_z1:.1f}]"
    )
    # DESIGN.md wants this asserted explicitly even though the two features
    # are obviously far apart -- require a comfortable literal margin, not
    # just "doesn't overlap".
    x_margin = min(abs(pivot_x - engrave_x0), abs(pivot_x - engrave_x1))
    z_margin = min(abs(pivot_z - engrave_z0), abs(pivot_z - engrave_z1))
    assert max(x_margin, z_margin) >= 10.0, (
        f"pivot hole only {min(x_margin, z_margin):.1f}mm from the engrave zone on "
        f"its nearest axis (want >= 10mm clear margin)"
    )


# =============================================================================
# C. Turn-button hardware pieces
# =============================================================================

def test_hardware_has_two_button_pieces(hardware_svg):
    pieces = su.design_pieces(hardware_svg)
    assert len(pieces) == 2, f"expected 2 turn-button pieces, found {len(pieces)}"
    for p in pieces:
        assert len(p.holes) == 1, f"{p.label!r} should carry exactly its own pivot hole"


def test_button_pivot_hole_present_and_sized(hardware_svg):
    for piece in su.design_pieces(hardware_svg):
        holes = [
            h for h in piece.holes
            if h.bbox.dims_match(EXPECTED_PIVOT_DRAWN_DIA, EXPECTED_PIVOT_DRAWN_DIA, tol=0.1)
        ]
        assert len(holes) == 1, f"{piece.label!r} missing its Ø{c.TURN_BUTTON['pivot_hole_dia']}mm pivot hole"


def test_button_reach_is_sufficient(hardware_svg):
    """Measured tip-to-pivot distance must be >= (LID_SLOT_TOP + 3) -
    TURN_BUTTON_PIVOT_Z (DESIGN.md: rotated to vertical, the tip must clear
    the slot's top edge by >= 3mm)."""
    required_reach = (c.LID_SLOT_TOP + 3.0) - c.TURN_BUTTON_PIVOT_Z
    for piece in su.design_pieces(hardware_svg):
        hole = [
            h for h in piece.holes
            if h.bbox.dims_match(EXPECTED_PIVOT_DRAWN_DIA, EXPECTED_PIVOT_DRAWN_DIA, tol=0.1)
        ][0]
        pivot_x = (hole.bbox.xmin + hole.bbox.xmax) / 2
        # The tip is the piece's own farthest point from the pivot along its
        # long (X) axis -- the paddle's blunt end is at the pivot, the tip
        # is the opposite end.
        reach = max(abs(pivot_x - piece.bbox.xmin), abs(piece.bbox.xmax - pivot_x))
        assert reach >= required_reach, (
            f"{piece.label!r}: measured reach {reach:.2f}mm < required {required_reach:.2f}mm"
        )


def test_buttons_do_not_overlap_in_nest(hardware_svg):
    pieces = su.get_pieces(hardware_svg)
    for i in range(len(pieces)):
        for j in range(i + 1, len(pieces)):
            assert not pieces[i].bbox.overlaps(pieces[j].bbox), (
                f"{pieces[i].label!r} overlaps {pieces[j].label!r} in {hardware_svg.name}"
            )


# =============================================================================
# D. Magnet press-fit coupon
# =============================================================================

def test_magnet_coupon_has_one_piece_and_four_holes(magnet_coupon_svg):
    pieces = su.get_pieces(magnet_coupon_svg)
    assert len(pieces) == 1
    assert len(pieces[0].holes) == 4


def test_magnet_coupon_hole_diameters(magnet_coupon_svg):
    from faxbox import calibration as cal

    piece = su.get_pieces(magnet_coupon_svg)[0]
    holes = sorted(piece.holes, key=lambda h: h.bbox.xmin)
    assert len(cal.MAGNET_COUPON_DIAMETERS) == 4
    for hole, nominal in zip(holes, cal.MAGNET_COUPON_DIAMETERS):
        # Burn-neutral (raw ctx circle), unlike the drawer/divider magnet
        # holes -- see calibration.py's module comment for why.
        assert abs(hole.bbox.width - nominal) <= 0.05, (
            f"magnet coupon hole nominal {nominal}mm measured {hole.bbox.width:.3f}mm "
            f"(expected burn-neutral, +/-0.05)"
        )
    assert min(cal.MAGNET_COUPON_DIAMETERS) < c.MAGNET_HOLE_DIA < max(cal.MAGNET_COUPON_DIAMETERS), (
        "coupon should span the current MAGNET_HOLE_DIA guess"
    )


def test_magnet_coupon_all_strokes_blue(magnet_coupon_svg):
    for p in su.iter_paths(magnet_coupon_svg):
        assert su.normalize_color(p.stroke) == "blue", (
            f"magnet coupon has a non-blue stroke: {p.stroke!r} (nothing on it is engraved)"
        )
